### ISSUE TITLE
Better order the sga helm chart to deploy the pods in the best order

### ISSUE THREAD

**Issue by dave2wave** [LangStream/langstream#184]
I noticed that when deploying with the helm chart to minikube many of the pods restarted several times. This was due to two reasons. 
1. Minikube was doing too much at once and the health checks failed.
2. Some pods are dependent on other pods being functional.

The `sga-cli` and `sga-control-plane` should be first.

**Comment by nicoloboschi** [comment]
You can disable each component by setting replicaCount to 0
