### ISSUE TITLE
Make secrets optional when updating application

### ISSUE THREAD

**Issue by ddieruf** [LangStream/langstream#188]
Sometimes you want to update an existing application but don't have the original secret values. Currently, an update that requires all manifests uses the PUT verb. Could the UPDATE verb be used to represent an update to certain parts of an application?

To specify that the secrets be removed using the UPDATEverb , provide a blank secrets file. Then all existing secrets would be removed and no new secrets would be created.

To specify that the secrets should remain unchanged up all other areas (pipeline, configuration, instance) be updated, don't provide any secrets file.

With this, you could create a separation of role. Where the platform operator creates the tenant, a security person "inits" an example application with all the needed secrets, and a developer updates with the intended function. The security person could provide a schema of secrets, for the developer to consume (but never see the actual values).

**Comment by nicoloboschi** [comment]
Already done
