### ISSUE TITLE
Cli: allow to deploy applications from a remote source (via http or git protocol)

### ISSUE THREAD

**Issue by nicoloboschi** [LangStream/langstream#292]
Currently all the files must be local.
There are some cases when you want to get the application pipeline from a remote source (maybe as an example).

## HTTP

It should be possible to specify a file from a remote source and download it using http protocol. 
For instance and secrets, it's easy because they're single file.
For application, this approach is fine if the pipeline is single file.

```
langstream apps deploy myapp -app https://langstream.ai/samples/pipeline.yaml -i https://my-internal-service/instanceyaml  -s https://my-internal-service/secrets/secret.yaml 
```

One possibility would be to support multiple yaml manifest in a single file.
Since LangStream expects a specific directories structure, this won't work with custom processors.
However, it covers many other cases.

## Git
One possibility would be to pass a git repo url targeting a specific folder. 
There's no standard for downloading a single directory from a git or github repository so it won't be a standard syntax.
I'd expect a cli command like this:

```
langstream apps deploy myapp -app git@github.com:<org>/<repo>.git/<folder> ...
```

**Comment by eolivelli** [comment]
how would you pass a "directory "?

we could allow to configure multiple pipelines in one file, but that won't help in the case of Python agents

**Comment by eolivelli** [comment]
maybe we could support packaging apps as zip files, but I didn’t want to go that way
because we would implicitly create our own “archive file” type, like jar, nar, wheel…

**Comment by eolivelli** [comment]
Released
