### ISSUE TITLE
langstream deployment issues on Azure AKS

### ISSUE THREAD

**Issue by sreyabondada** [LangStream/langstream#402]
I am installing langstream in Azure Kubernetes Service environment, I have followed the steps for the deployment in the kubernetes.. I have used helm charts for the install.. I used the below commands for the deployment..

helm repo add langstream https://langstream.github.io/charts
helm repo update
helm install -n langstream --create-namespace langstream langstream/langstream --values helm/examples/simple.yaml

naga_bondada [ ~/langstream ]$ kubectl get pods -n langstream
NAME                                        READY   STATUS             RESTARTS         AGE
langstream-api-gateway-79bd776d6-2npsd      1/1     Running            0                31m
langstream-client-d5b455cc6-gwd4d           1/1     Running            0                31m
langstream-control-plane-7b7fb7ffc5-bj85h   0/1     CrashLoopBackOff   10 (4m15s ago)   31m
langstream-deployer-57b6565484-zsjxx        1/1     Running            0                31m
naga_bondada [ ~/langstream ]$ 

I am unable to find runtime pod in the list of pods.. below is the output from the control plane pods logs..

[controlplane-pod-logs.txt](https://github.com/LangStream/langstream/files/12596466/controlplane-pod-logs.txt)

Please help me in resolving this issue to proceed further..

Suresh

**Comment by nicoloboschi** [comment]
@sreyabondada 👋 

Some questions:
- Which versions are you using of Langstream? 
The control plane seems on an old version


>I am unable to find runtime pod in the list of pods

This is fine. The runtime pod is scheduled only if you create an application

**Comment by sreyabondada** [comment]
Hi Nicolo
Thanks for your reply, its working now.. which document we need to use going further.. 
Please suggest.

Regards
Suresh

**Comment by nicoloboschi** [comment]
@sreyabondada I updated the readme and that values file.

First of all you need to configure the code storage, you can find instructions [here](https://github.com/LangStream/langstream/tree/main/helm)
You either setup a local MinIO instance or use a real S3 bucket.

Once you're there, you are able to deploy applications.

First, install the CLI: https://docs.langstream.ai/installation/langstream-cli
Then create your application. You can take a look at the [examples](https://github.com/LangStream/langstream/tree/main/examples/applications) directory. 

Additionally, here is the official [documentation](https://docs.langstream.ai/get-started#your-first-application)

**Comment by sreyabondada** [comment]
Hi Nicolo

We have one more query, We are setting up langstream on Azure and we got to know Azure Blob Storage doesn't support S3 protocol.. how we can make use of langstream in that scenerio.. Could you please throw some light here.

Regards
Suresh
