### ISSUE TITLE
Error while testing OpenAI-completions application?

### ISSUE THREAD

**Issue by sreyabondada** [LangStream/langstream#409]
Hi Team,

We have successfully setup lang stream and we have deployed the OpenAI-Completions application. When we are trying to run the following command 

/bin/langstream gateway chat test -cg consume-output -pg produce-input -p sessionId=$(uuidgen)

we are getting the folllowing error..

naga_bondada [ ~/langstream ]$ langstream gateway chat test1 -cg consume-output -pg produce-input -p sessionId=$(uuidgen)
Handling connection for 8090
Handling connection for 8091
The HTTP response from the server [500] did not permit the HTTP upgrade to WebSocket.

[ ~/langstream ]$ kubectl get pods -n langstream
NAME                                        READY   STATUS    RESTARTS   AGE
langstream-api-gateway-658759b8dd-twszp     1/1     Running   0          17h
langstream-client-75fc54db48-2xsn9          1/1     Running   0          17h
langstream-control-plane-7f98f96d8c-9q4vq   1/1     Running   0          17h
langstream-deployer-64bb46c4c6-hnzks        1/1     Running   0          17h

Please help me to fix this issue, 

Regards
Suresh

**Comment by nicoloboschi** [comment]
Hi @sreyabondada you can check the langstream-api-gateway pod logs to see the actual error

Also if you have other quick questions you can reach me on slack https://join.slack.com/t/langstream/shared_invite/zt-21leloc9c-lNaGLdiecHuWU5N31L2AeQ

**Comment by sreyabondada** [comment]
Hi 

Here are the logs you have requested.. Please go thru this..

Regards
Suresh
[logs-apigateway.txt](https://github.com/LangStream/langstream/files/12607237/logs-apigateway.txt)

**Comment by nicoloboschi** [comment]
the problem was on kafka, closing
