### ISSUE TITLE
Add support for the OpenAI completion API

### ISSUE THREAD

**Issue by cdbartholomew** [LangStream/langstream#445]
Currently we support the OpenAI ChatCompletions API since that is the only API that supports the more powerful models (`gpt-3.5-turbo`, `gpt-4`). Yesterday, OpenAI released the instruct version of the gpt-3.5-turbo model. This model has not been trained for chat interactions but just following instructions. For autonomous agents, the chat model is not useful and can be cumbersome to deal with (ex. need extra prompt engineering to stop it from being "chatty"). This instruct model will likely become increasingly popular and we should support it.

The `gpt-3.5-turbo-instruct` model uses the Completion API. It is a simple text-in, text-out API. We should add an agent configuration that will use it.

**Comment by eolivelli** [comment]
released in 0.0.22
