### ISSUE TITLE
Add re-ranking agent

### ISSUE THREAD

**Issue by cdbartholomew** [LangStream/langstream#447]
In the context of vector storees, reranking computes a relevance score between the query and each data object, and returns the list of objects sorted from the most to the least relevant. This can be used to improve the quality of the results returned by the vector database.

In LangStream we should implement a re-ranking agent that takes the raw results from a vector similarity search, re-ranks them, and returns the results. This agent would typically run after the vector query and before the prompt construction, but it could also run as part of a standalone re-ranking pipeline.

The re-ranking agent should support multiple methods for re-ranking. Here are some re-ranking method options:

* Standard rerankers, for example MMR
* Vendor rerankers, such as cohere API
* Rerank based on metadata, ex order volume, CTR, ratings scores, etc.

The first version of the re-ranking agent should support MMR at least.

**Comment by eolivelli** [comment]
implemented with #502
