### ISSUE TITLE
Generate agents config documentation automatically

### ISSUE THREAD

**Issue by nicoloboschi** [LangStream/langstream#500]
The more agents get added/updated, the more docs we need to write manually. 
I propose to use a tool to generate a JSON file with the configuration for each agent.

To get all the available agents in a specific LangStream version, we add a command in the "langstream-runtime" image to generate the json.
The command will use reflections to gather the definitions of each agent. The configuration must be a java class with custom annotations.

For the annotations, I was thinking of implementing something very similar to Pulsar IO: https://github.com/apache/pulsar/blob/09a17203702a032274a56d7d0ff03c9e32b4529f/pulsar-io/core/src/main/java/org/apache/pulsar/io/core/annotations/FieldDoc.java#L34

There's no *standard* for documenting static properties and it's better to have our own system to ease further developments.

The JSON format will be well-defined and documented. 

The final step would be to generate a markdown from the JSON and create a Agents API Reference in the doc (this will happen in the documentation repository).

**Comment by eolivelli** [comment]
we should provide an API on the control plane to serve this information, this way the VS Code extension can interpret the pipelines and also build dynamically code snippets

cc @ddieruf

**Comment by nicoloboschi** [comment]
Automatic doc generation for agents, assets and resources has been released in 0.1.0 

For the VS code extension, we will load the static json directly
