### ISSUE TITLE
CLI Command to generate a mermaid chart from the application definition

### ISSUE THREAD

**Issue by cbornet** [LangStream/langstream#523]
Should it generate on the deployment dir before deploying ?
Or on the deployed app (get app -o mermaid) ?
Or both ?

We could also use a dockerized mermaid-cli to generate SVG.

**Comment by cdbartholomew** [comment]
Ideally, it would be able to generate the chart without having to first deploy the app. Assuming we are going to do this server side, does that make it tricky to do on an undeployed app?

**Comment by eolivelli** [comment]
There are two things that you would like to see:
- the logical application (this can be done statically by the CLI, but maybe it doesn't match the server side features)
- the execution plan (this requires the control plane at least)

I think that we can add an API to the control plane to render both of them, together with the final yaml after applying global variables (and secrets), but without deploying the application.
We can of course do the same for a deployed application.

**Comment by cbornet** [comment]
> but maybe it doesn't match the server side features

Which server-side feature are you referring to ?

**Comment by nicoloboschi** [comment]
With the new `--dry-run` flag, this could be done easily on client-side by just adding a new format `-o mermaid`

**Comment by cbornet** [comment]
Yes. It seems to fit the `dry-run` op

**Comment by eolivelli** [comment]
This task seems done, now we have Mermaid integrated with the "docker" UI
