### ISSUE TITLE
Cli: add command to resolve placeholders locally 

### ISSUE THREAD

**Issue by nicoloboschi** [LangStream/langstream#532]
It could be very useful to have a CLI command that resolves all the placeholder, for debugging purposes. It would be similar to [Helm template](https://helm.sh/docs/helm/helm_template/).

The output would be sent to stdout.

**Comment by nicoloboschi** [comment]
since the CLI doesn't import langstream-core for several reasons, it's not possible to run the parser+resolver code locally.
We could add an endpoint in the control plane instead

**Comment by eolivelli** [comment]
The output could look like helm, dumping al the manifests
