### ISSUE TITLE
Run simple gateway UI from CLI

### ISSUE THREAD

**Issue by nicoloboschi** [LangStream/langstream#545]
Currently the chat gateway command works fine. However running it in a browser would be much more friendly for users.

I propose to add a flag in the CLI command to deploy a UI locally and open the browser

## Implementation

The UI will be smart about the application to reduce friction for the user:
* it reads the application configuration and loads all the possible gateways
* in the UI let the user to choose a chat-bot like configuration: questions gateway and answers gateway. If only one specified, will be already setup
* possible authentication steps (if required by the gateway) - this might be addressed later
* Chat UI to produce and consume
* Support for "chat" type gateway

We can start from this example for the UI: https://github.com/LangStream/langstream/tree/main/examples/websockets/openai-completions-chatbot
We can improve UI & usability step by step. 

This html file will be distributed in the CLI so it'd be versioned as well.

Another great point of this is that this would be a real "reference" implementation for gateway client because it'd be maintained (since it's distributed and part of the release)

## FInal result
Users deploy any application and then run 
```
langstream gateway ui
```
It opens the browser at the page with everything set-up to write to a produce topic and see the response.

**Comment by eolivelli** [comment]
Delivered in 0.2.0
