### ISSUE TITLE
Create an application for postgres sink

### ISSUE THREAD

**Issue by ksaurabh21** [LangStream/langstream#561]
Please create an example application for a postgres sink pipeline that can read a message from a topic and write to a table in postgres.
For example say, there is a topic called human_response where any user query first lands. This pipeline will take the message and store the information such as the user's query, timestamp of the message, session-id, etc into a table called conversation_history.

**Comment by eolivelli** [comment]
Here you can find how to connect to Postgresql
https://github.com/LangStream/langstream/tree/main/examples/applications/query-postgresql

**Comment by eolivelli** [comment]
Here you can find how to handle jdbc table assets
https://docs.langstream.ai/building-applications/assets

**Comment by eolivelli** [comment]
This is the full reference for jdbc and langstream
https://docs.langstream.ai/integrations/data-storage/jdbc

**Comment by eolivelli** [comment]
I agree that we should add some examples about how to store the history.

I know that @cdbartholomew has some examples

**Comment by nicoloboschi** [comment]
One useful addition it would be to have an agent to write SQL for writes, like "query"

**Comment by eolivelli** [comment]
@ksaurabh21 this implementation will provide you the support to write the chat history
https://github.com/LangStream/langstream/pull/605

**Comment by eolivelli** [comment]
@ksaurabh21 this is the sample application that you have asked for
https://github.com/LangStream/langstream/tree/main/examples/applications/query-postgresql-chat-history
it is still lacking support for removing stale chat history, stay tuned (a follow-up patch is coming) 

The application needs #605 so you will be able to use it only with the upcoming release of LangStream (0.3.x) of if you build the main branch locally

**Comment by eolivelli** [comment]
@ksaurabh21 thanks for sharing your alternative.

Please also note that now we have a way to purge automatically the history using a "timer-source"
https://github.com/LangStream/langstream/blob/main/examples/applications/query-postgresql-chat-history/clean-history.yaml

In 0.3.0 we have added a few new agents to help with flow control and activation:
- timer-source
- trigger-event
- log-event
