### ISSUE TITLE
CLI setup script failing due to cannot find zip file

### ISSUE THREAD

**Issue by cdbartholomew** [LangStream/langstream#572]
Reported by Jagannath S Bilgi in Slack.

Trying to setup langstream CLI on GKE cluster using following command.
"sudo curl -Ls "https://raw.githubusercontent.com/LangStream/langstream/main/bin/get-cli.sh" | bash"
However getting below error.
"unzip:  cannot find zipfile directory in one of /home/jagannath_bilgi/.langstream/downloads/langstream-cli-0.2.0.zip or
        /home/jagannath_bilgi/.langstream/downloads/langstream-cli-0.2.0.zip.zip, and cannot find /home/jagannath_bilgi/.langstream/downloads/langstream-cli-0.2.0.zip.ZIP, period.
'ARCHIVE_OK=$(unzip -qt "$downloaded_zip_path" | grep 'No errors detected in compressed data')': command failed with exit code 1."
Note: Have verified that "langstream-cli-0.2.0.zip" file is present.
Attached snippet for reference. Kindly advise how to resolve the same
 
![image](https://github.com/LangStream/langstream/assets/22917476/26004094-447b-42da-b4ac-3620c9d27b52)

**Comment by cdbartholomew** [comment]
@nicoloboschi Any ideas on why this is failing?

**Comment by nicoloboschi** [comment]
It was a temporary error during the download (from a previous command). 
The solution was to delete the zip and re-run the installation

I don't think we need to handle this case in the installer
