### ISSUE TITLE
Error message can be improved for missing configuration resource

### ISSUE THREAD

**Issue by ksaurabh21** [LangStream/langstream#595]
I was getting this error when trying to use "ai-chat-completions". The reason was "open-ai-configuration" was not defined in the configuration.yaml. May be the error message can be improved to indicate missing configuration:

`[openaichat-pipeline-ai-chat-completions-3-0]   at ai.langstream.runtime.agent.AgentRunnerStarter.start(AgentRunnerStarter.java:111)
[openaichat-pipeline-ai-chat-completions-3-0]   at ai.langstream.runtime.agent.AgentRunnerStarter.main(AgentRunnerStarter.java:53)
[openaichat-pipeline-ai-chat-completions-3-0]   at ai.langstream.runtime.Main.main(Main.java:42)
[openaichat-pipeline-ai-chat-completions-3-0] 14:57:26.274 [main] ERROR a.l.runtime.agent.AgentRunnerStarter -- Unexpected error
[openaichat-pipeline-ai-chat-completions-3-0] java.lang.IllegalArgumentException: No AI ServiceProvider found for resource {type=ai-chat-completions, when=null, model=gpt35-16k-0631, messages=[{role=user, content={{ value.prompt}}}], stream-to-topic=bot-response-stream, stream-response-completion-field=value, min-chunks-per-message=10, completion-field=value.answer, stream=true, log-field=value.log, max-tokens=null, temperature=null, top-p=null, logit-bias=null, user=null, stop=null, presence-penalty=null, frequency-penalty=null}
[openaichat-pipeline-ai-chat-completions-3-0]   at ai.langstream.ai.agents.services.ServiceProviderRegistry$NoServiceProvider.getCompletionsService(ServiceProviderRegistry.java:36)
`

**Comment by nicoloboschi** [comment]
this was in docker run IIRC 
I think we bypass the validation in docker run 🤔 we shouldn't
