### ISSUE TITLE
Apps in the ERROR_DEPLOYING state cannot be deleted and logs aren't avaliable

### ISSUE THREAD

**Issue by mfortman11** [LangStream/langstream#638]
When creating an app and it fails in the `ERROR_DEPLOYING` state logs are unavailable (receives a `No pods found`)

When I delete the app the operation appears to be successful but the app remains in the apps list

If I attempt to update the app I get a 400 and a `Application {app name} is marked for deletion.`

**Comment by nicoloboschi** [comment]
Fixed by #714

Released in 0.4.4

cc @mfortman11
