### ISSUE TITLE
null safety for VectorDatabaseWriterProviderRegistry

### ISSUE THREAD

**Issue by mukundha** [LangStream/langstream#651]
[VectorDatabaseWriterProviderRegistry](https://github.com/LangStream/langstream/blob/main/langstream-api/src/main/java/ai/langstream/api/database/VectorDatabaseWriterProviderRegistry.java#L39)

think `store.createImplementation(configuration);` needs to be `store.createImplementation(conf);`

```
Map<String, Object> conf = configuration == null ? Map.of() : configuration;
...
...
 return store.createImplementation(configuration);
```

Issue:
```
java.lang.NullPointerException: Cannot invoke "Object.toString()" because the return value of "java.util.Map.getOrDefault(Object, Object)" is null
	at ai.langstream.agents.vector.cassandra.CassandraWriter$CassandraVectorDatabaseWriter.lambda$initialise$0(CassandraWriter.java:103)
```
I also would need to find when the configuration will be null

**Comment by eolivelli** [comment]
Fixed with #653
