### ISSUE TITLE
write-to-astra sink to support JSON API

### ISSUE THREAD

**Issue by mukundha** [LangStream/langstream#727]
AstraDB just previewed the Vector / JSON-first experience. It will be good for write-to-astra sink to support JSON API, so it works well with the new experience and helps developers who are new to cassandra to get started easily.

There is a Java SDK for using the JSON API
https://docs.datastax.com/en/astra/astra-db-vector/get-started/quickstart.html

cc @cdbartholomew

**Comment by eolivelli** [comment]
@mukundha I have started to work on this (see #731 )

**Comment by eolivelli** [comment]
@mukundha This has been delivered with 0.5.0 today.
We are going to update the docs as soon as possible.
you can check #731 is you want to take a look, there is a new example application
